// src/pages/Dashboard.jsx
import React from 'react';
import { Card, Row, Col, Statistic, List, Tag, Table } from 'antd';
import { 
  LinkOutlined, 
  GlobalOutlined, 
  TagsOutlined, 
  FolderOutlined 
} from '@ant-design/icons';
import useSWR from 'swr';
import { bookmarkAPI } from '../services/api';

const Dashboard = () => {
  const { data: stats, error } = useSWR('/stats', bookmarkAPI.getStats);

  if (error) return <div>加载失败</div>;
  if (!stats) return <div>加载中...</div>;

  return (
    <div>
      <Row gutter={[16, 16]}>
        {/* 统计卡片 */}
        <Col span={6}>
          <Card>
            <Statistic
              title="总书签数"
              value={stats.bookmarks}
              prefix={<LinkOutlined />}
            />
          </Card>
        </Col>
        <Col span={6}>
          <Card>
            <Statistic
              title="域名数"
              value={stats.domains}
              prefix={<GlobalOutlined />}
            />
          </Card>
        </Col>
        <Col span={6}>
          <Card>
            <Statistic
              title="标签数"
              value={stats.tags}
              prefix={<TagsOutlined />}
            />
          </Card>
        </Col>
        <Col span={6}>
          <Card>
            <Statistic
              title="分类数"
              value={stats.categories}
              prefix={<FolderOutlined />}
            />
          </Card>
        </Col>
      </Row>

      <Row gutter={[16, 16]} style={{ marginTop: 16 }}>
        {/* 热门域名 */}
        <Col span={12}>
          <Card title="热门域名">
            <Table
              dataSource={stats.topDomains}
              pagination={false}
              columns={[
                {
                  title: '域名',
                  dataIndex: 'domain',
                  key: 'domain',
                },
                {
                  title: '书签数',
                  dataIndex: 'count',
                  key: 'count',
                },
              ]}
            />
          </Card>
        </Col>

        {/* 热门标签 */}
        <Col span={12}>
          <Card title="热门标签">
            <div style={{ padding: '8px' }}>
              {stats.topTags.map(({ tag, count }) => (
                <Tag key={tag} style={{ margin: '4px' }}>
                  {tag} ({count})
                </Tag>
              ))}
            </div>
          </Card>
        </Col>
      </Row>

      {/* 最近更新 */}
      <Row style={{ marginTop: 16 }}>
        <Col span={24}>
          <Card title="最近更新的书签">
            <List
              dataSource={stats.recentBookmarks}
              renderItem={item => (
                <List.Item>
                  <List.Item.Meta
                    title={item.title}
                    description={
                      <>
                        <Tag>{item.domain}</Tag>
                        {item.tags?.map(tag => (
                          <Tag key={tag} color="blue">{tag}</Tag>
                        ))}
                      </>
                    }
                  />
                  <div>{new Date(item.updatedAt).toLocaleString()}</div>
                </List.Item>
              )}
            />
          </Card>
        </Col>
      </Row>
    </div>
  );
};

export default Dashboard;

// src/views/Dashboard.vue
<template>
  <div class="dashboard">
    <el-row :gutter="20">
      <el-col :span="6">
        <el-card class="stat-card">
          <h3>总书签数</h3>
          <div class="stat-value">{{ stats.bookmarks }}</div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card class="stat-card">
          <h3>总域名数</h3>
          <div class="stat-value">{{ stats.domains }}</div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card class="stat-card">
          <h3>总标签数</h3>
          <div class="stat-value">{{ stats.tags }}</div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card class="stat-card">
          <h3>总分类数</h3>
          <div class="stat-value">{{ stats.categories }}</div>
        </el-card>
      </el-col>
    </el-row>

    <el-row :gutter="20" class="mt-4">
      <el-col :span="12">
        <el-card>
          <template #header>
            <div class="card-header">
              <span>热门域名</span>
            </div>
          </template>
          <el-table :data="stats.topDomains">
            <el-table-column prop="domain" label="域名" />
            <el-table-column prop="count" label="书签数" width="100" />
          </el-table>
        </el-card>
      </el-col>
      
      <el-col :span="12">
        <el-card>
          <template #header>
            <div class="card-header">
              <span>热门标签</span>
            </div>
          </template>
          <el-table :data="stats.topTags">
            <el-table-column prop="tag" label="标签" />
            <el-table-column prop="count" label="使用次数" width="100" />
          </el-table>
        </el-card>
      </el-col>
    </el-row>

    <el-row class="mt-4">
      <el-col :span="24">
        <el-card>
          <template #header>
            <div class="card-header">
              <span>最近更新</span>
            </div>
          </template>
          <el-table :data="stats.recentBookmarks">
            <el-table-column prop="title" label="标题" min-width="200" />
            <el-table-column prop="domain" label="域名" width="180" />
            <el-table-column prop="updatedAt" label="更新时间" width="180">
              <template #default="{ row }">
                {{ new Date(row.updatedAt).toLocaleString() }}
              </template>
            </el-table-column>
          </el-table>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import api from '@/api/bookmarks'

const stats = ref({
  bookmarks: 0,
  domains: 0,
  tags: 0,
  categories: 0,
  topDomains: [],
  topTags: [],
  recentBookmarks: []
})

const fetchStats = async () => {
  try {
    const { data } = await api.getStats()
    stats.value = data
  } catch (error) {
    console.error('Failed to fetch stats:', error)
  }
}

onMounted(() => {
  fetchStats()
})
</script>

<style scoped>
.dashboard {
  padding: 20px;
}

.stat-card {
  text-align: center;
}

.stat-value {
  font-size: 24px;
  font-weight: bold;
  color: #409EFF;
  margin-top: 10px;
}

.mt-4 {
  margin-top: 16px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>
